# Generated by Django 5.2.13 on 2026-09-08 22:45

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id_ruta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('origen', models.CharField(max_length=200)),
                ('destino', models.CharField(max_length=200)),
                ('geometria_ruta', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
                ('punto_origen', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('punto_destino', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('paradas', django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326)),
                ('num_paradas', models.IntegerField(default=0)),
                ('distancia_km', models.FloatField(default=0)),
                ('duracion_estimada_minutos', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva'), ('fuera_servicio', 'Fuera de Servicio')], default='activa', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('latitud', models.FloatField(default=0)),
                ('longitud', models.FloatField(default=0)),
                ('paradas_count', models.IntegerField(default=0)),
                ('duracion_estimada', models.TimeField(default='00:00:00')),
                ('frecuencia', models.TimeField(default='00:00:00')),
            ],
            options={
                'verbose_name': 'Ruta de Autobús',
                'verbose_name_plural': 'Rutas de Autobuses',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('contrasena', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('nickName', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id_conductor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('cedula', models.CharField(max_length=50, unique=True)),
                ('contrasena', models.CharField(max_length=40)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conductores', to='core.ruta')),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id_bus', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='core.ruta')),
            ],
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id_alerta', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='core.ruta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='core.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='UbicacionBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='core.bus')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones_bus', to='core.ruta')),
            ],
            options={
                'verbose_name': 'Ubicación de Bus',
                'verbose_name_plural': 'Ubicaciones de Buses',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['bus', 'timestamp'], name='core_ubicac_bus_id_f55401_idx'), models.Index(fields=['ruta', 'timestamp'], name='core_ubicac_ruta_id_ab156f_idx')],
            },
        ),
    ]
