# Generated by Django 5.2.13 on 2026-07-01 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id_ruta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('origen', models.CharField(max_length=200)),
                ('destino', models.CharField(max_length=200)),
                ('distancia_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracion_estimada', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(choices=[('Activa', 'Activa'), ('Inactiva', 'Inactiva'), ('Mantenimiento', 'En Mantenimiento')], default='Activa', max_length=50)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
