# Generated by Django 6.0.4 on 2026-09-10 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='longitud',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='paradas_count',
        ),
        migrations.AlterField(
            model_name='ruta',
            name='destino',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='estado',
            field=models.CharField(choices=[('Activa', 'Activa'), ('Inactiva', 'Inactiva'), ('Fuera_servicio', 'Fuera de Servicio')], default='Activa', max_length=20),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='origen',
            field=models.CharField(),
        ),
    ]
