# Generated by Django 6.0.5 on 2026-09-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bus',
            name='ultima_ubicacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
