# Generated by Django 5.2.13 on 2026-08-26 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='distancia_km',
        ),
        migrations.AddField(
            model_name='ruta',
            name='frecuencia',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='paradas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='duracion_estimada',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='estado',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id_bus', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='core.ruta')),
            ],
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id_conductor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('cedula', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=40)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conductores', to='core.ruta')),
            ],
        ),
        migrations.AddField(
            model_name='ruta',
            name='distancia_Km',
            field=models.FloatField(default=0),
        ),
    ]
