# Generated by Django 5.2.13 on 2026-08-27 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_ruta_descripcion_remove_ruta_distancia_km_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('contrasena', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('nickName', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='conductor',
            name='cedula',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='telefono',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id_alerta', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='core.ruta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='core.usuario')),
            ],
        ),
    ]
