# Generated by Django 6.0.4 on 2026-09-10 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_ruta_latitud_remove_ruta_longitud_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='frecuencia',
        ),
        migrations.AddField(
            model_name='ruta',
            name='frecuencia_minutos',
            field=models.IntegerField(default=0),
        ),
    ]
