# Generated by Django 6.0.4 on 2026-09-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usuario_alter_conductor_cedula_alter_conductor_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='latitud',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ruta',
            name='longitud',
            field=models.FloatField(default=0),
        ),
    ]
