# Generated by Django 6.0.4 on 2026-09-10 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_ruta_frecuencia_ruta_frecuencia_minutos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='frecuencia_minutos',
        ),
        migrations.AddField(
            model_name='ruta',
            name='frecuencia',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
