# Generated by Django 6.0.4 on 2026-09-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_ruta_frecuencia_minutos_ruta_frecuencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='duracion_estimada',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='frecuencia',
        ),
        migrations.AddField(
            model_name='ruta',
            name='frecuencia_minutos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='destino',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='origen',
            field=models.CharField(max_length=300),
        ),
    ]
