# Generated by Django 6.0.4 on 2026-09-10 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_ruta_duracion_estimada_remove_ruta_frecuencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='descripcion',
        ),
    ]
