# Generated by Django 6.0.5 on 2026-09-10 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bus_activo_bus_ultima_ubicacion'),
        ('core', '0006_remove_ruta_descripcion'),
    ]

    operations = [
    ]
