# Generated by Django 6.0.4 on 2026-09-14 16:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_merge_20260910_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacionbus',
            name='velocidad',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='codigo_expiracion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='codigo_recuperacion',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nickName',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='El teléfono debe contener solo números (entre 7 y 15 dígitos).', regex='^\\d{7,15}$')]),
        ),
    ]
