# Generated by Django 6.0.4 on 2026-09-15 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_usuario_foto_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='foto_perfil',
        ),
    ]
