# Generated by Django 6.0.4 on 2026-09-15 16:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='color_perfil',
            field=models.CharField(default='#E63946', help_text='Color hex del avatar (ej: #E63946)', max_length=7),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nickName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='El teléfono debe contener solo números (entre 7 y 15 dígitos).', regex='^\\d{7,15}$')]),
        ),
    ]
