# Generated by Django 6.0.4 on 2026-09-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_usuario_color_perfil_alter_usuario_nickname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='color_perfil',
            field=models.CharField(default='#E63946', max_length=7),
        ),
    ]
